### ISSUE TITLE
New filters in builtin module

### ISSUE THREAD

**Issue by JrooTJunior** [aiogram/aiogram#151]
Next list of filters is planned for implementation in [builtin](https://github.com/aiogram/aiogram/blob/dev-2.x/aiogram/dispatcher/filters/builtin.py) module and registered in filters factory:
- [x] Chat id  ([aiogram#1544](https://t.me/aiogram/1544)) - PR: #172 
- [x] User id ([aiogram#1544](https://t.me/aiogram/1544)) - PR: #172 
- [x] User is admin in chat ([aiogram#1549](https://t.me/aiogram/1549), [aiogram#1555](https://t.me/aiogram/1555)) - PR: #182 
- [x] Message is reply to another message ([aiogram#1549](https://t.me/aiogram/1549)) - PR: #210, #212
- [x] Message forwarded ([aiogram#1549](https://t.me/aiogram/1549)) - PR: #355
- [x] Move [chat type filters](https://github.com/aiogram/aiogram/blob/dev-2.x/aiogram/types/chat.py#L431-L479) ([aiogram#1549](https://t.me/aiogram/1549))
- [x] Multiple text filter ([aiogram_ru#73126](https://t.me/aiogram_ru/73126))
- [x] check that the contact matches the sender - [commit](https://github.com/aiogram/aiogram/commit/5db726d7585c5252343642f1201c4775ac47bfeb)

**Comment by Birdi7** [comment]
I would like to work on Multiple text filter. But I have a question regarding the key word. Should it be `text` for both single and muliple elements, `text` for single and `texts` for a list, or `texts` for both single and multiple elements(like it's done in commands filter)? @JrooTJunior what do you think about it?

**Comment by Forevka69** [comment]
Maybe it will be useful:

Checking if message from group
```
class IsGroup(Filter):
    """
        Check if chat is group
    """

    async def check(self, obj: Union[Message, CallbackQuery], *args):
        if isinstance(obj, Message):
            return obj.chat.id < 0
        return obj.message.chat.id < 0
```

Check if message from private

```
class IsPrivate(Filter):
    async def check(self, obj: Union[Message, CallbackQuery], *args):
        return obj.chat.id == obj.from_user.id
```

Check message text in list 

```
class IsTextInList(Filter):
    def __init__(self, text_list):
        self.text_list = text_list

    async def check(self, obj: Union[Message, CallbackQuery], *args):
        return obj.text in self.text_list
```

**Comment by JrooTJunior** [comment]
@Forevka69, filters for chat types is already implemented in `types.ChatType` object:
https://github.com/aiogram/aiogram/blob/e77f5142b61fba2f642da9fab5b302b6fcd627c3/aiogram/types/chat.py#L423-L479

**Comment by JrooTJunior** [comment]
But i think chat type filter can be also implemented (with deprecation of current filters)

For example implement next opportunity:

- `@dp.message_handler(chat_type=types.ChatType.PRIVATE)`
- `@dp.message_handler(chat_type=[types.ChatType.GROUP, types.ChatType.SUPER_GROUP])`

**Comment by JrooTJunior** [comment]
About text in list...
I see no prerequisites for implementing separated filter. Maybe it can be added to `Text` filter.

**Comment by riZZZhik** [comment]
**Have a nice weekend**
`from_user=id`
`reply_to=id`
`forward_from=id`

**Comment by riZZZhik** [comment]
Maybe multiple all filters?

**Comment by JrooTJunior** [comment]
> multiple all filters?

What do you mean?

**Comment by riZZZhik** [comment]
> What do you mean?

optimize custom_filter return with Any()

**Comment by JrooTJunior** [comment]
> optimize custom_filter return with Any()

I don't understand
