### ISSUE TITLE
[Tracking] API 5.1

### ISSUE THREAD

**Issue by evgfilim1** [aiogram/aiogram#518]
_This is meta-issue for tracking new [Bot API 5.1 update](https://core.telegram.org/bots/api-changelog#march-9-2021)_

## Added two new update types

- [x] Added updates about member status changes in chats, represented by the class [`ChatMemberUpdated`](https://core.telegram.org/bots/api#chatmemberupdated) and the fields `my_chat_member` and `chat_member` in the `Update` class. The bot must be an administrator in the chat to receive `chat_member` updates about other chat members. By default, only `my_chat_member` updates about the bot itself are received.
- [x] (**aiogram**) Fix filters for new update types

## Improved Invite Links

- [x] Added the class [`ChatInviteLink`](https://core.telegram.org/bots/api#chatinvitelink), representing an invite link to a chat.
- [x] Added the method [`createChatInviteLink`](https://core.telegram.org/bots/api#createchatinvitelink), which can be used to create new invite links in addition to the primary invite link.
- [x] Added the method [`editChatInviteLink`](https://core.telegram.org/bots/api#editchatinvitelink), which can be used to edit non-primary invite links created by the bot.
- [x] Added the method [`revokeChatInviteLink`](https://core.telegram.org/bots/api#revokechatinvitelink), which can be used to revoke invite links created by the bot.

## Voice Chat Info

- [x] Added the type [`VoiceChatStarted`](https://core.telegram.org/bots/api#voicechatstarted) and the field `voice_chat_started` to the class `Message`.
- [x] Added the type [`VoiceChatEnded`](https://core.telegram.org/bots/api#voicechatended) and the field `voice_chat_ended` to the class `Message`.
- [x] Added the type [`VoiceChatParticipantsInvited`](https://core.telegram.org/bots/api#voicechatparticipantsinvited) and the field `voice_chat_participants_invited` to the class `Message`.
- [x] Added the new administrator privilege `can_manage_voice_chats` to the class `ChatMember` and parameter `can_manage_voice_chats` to the method `promoteChatMember`. For now, bots can use this privilege only for passing to other administrators.

## And More
- [x] Added the type [`MessageAutoDeleteTimerChanged`](https://core.telegram.org/bots/api#messageautodeletetimerchanged) and the field `message_auto_delete_timer_changed` to the class `Message`.
- [x] Added the parameter `revoke_messages` to the method `kickChatMember`, allowing to delete all messages from a group for the user who is being removed.
- [x] Added the new administrator privilege `can_manage_chat` to the class `ChatMember` and parameter `can_manage_chat` to the method `promoteChatMember`. This administrator right is implied by any other administrator privilege.
- [x] Supported the new bowling animation for the random dice. Choose between different animations (dice, darts, basketball, football, bowling, slot machine) by specifying the emoji parameter in the method `sendDice`.
