### ISSUE TITLE
[Tracking] Bot API 5.2

### ISSUE THREAD

**Issue by evgfilim1** [aiogram/aiogram#571]
## Bot API 5.2
- [ ] Support for [Payments 2.0](https://telegram.org/blog/payments-2-0-scheduled-voice-chats), see [this manual](https://core.telegram.org/bots/payments) for more details about the Bot Payments API.
- [x] Added the type [`InputInvoiceMessageContent`](https://core.telegram.org/bots/api#inputinvoicemessagecontent) to support sending invoices as inline query results.
- [x] Allowed sending invoices to group, supergroup and channel chats.
- [x] Added the fields `max_tip_amount` and `suggested_tip_amounts` to the method [`sendInvoice`](https://core.telegram.org/bots/api#sendinvoice) to allow adding optional tips to the payment.
- [x] The parameter `start_parameter` of the method [`sendInvoice`](https://core.telegram.org/bots/api#sendinvoice) became optional. If the parameter isn't specified, the invoice can be paid directly from forwarded messages.
- [x] Added the field `chat_type` to the class [`InlineQuery`](https://core.telegram.org/bots/api#inlinequery), containing the type of the chat, from which the inline request was sent.
- [x] Added the type [`VoiceChatScheduled`](https://core.telegram.org/bots/api#voicechatscheduled) and the field `voice_chat_scheduled` to the class [`Message`](https://core.telegram.org/bots/api#message).
- [x] Fixed an error in [`sendChatAction`](https://core.telegram.org/bots/api#sendchataction) documentation to correctly mention “record_voice” and “upload_voice” instead of “record_audio” and “upload_audio” for related to voice note actions. Old action names will still work for backward compatibility.
