### ISSUE TITLE
[Tracking] Bot API 5.3

### ISSUE THREAD

**Issue by evgfilim1** [aiogram/aiogram#611]
## Personalized Commands

- [x] Bots can now show lists of commands tailored to specific situations - including localized commands for users with different languages, as well as different commands based on chat type or for specific chats, and special lists of commands for chat admins.
- [x] Added the class [`BotCommandScope`](https://core.telegram.org/bots/api#botcommandscope), describing the scope to which bot commands apply.
- [x] Added the parameters `scope` and `language_code` to the method [`setMyCommands`](https://core.telegram.org/bots/api#setmycommands) to allow bots specify different commands for different chats and users.
- [x] Added the parameters `scope` and `language_code` to the method [`getMyCommands`](https://core.telegram.org/bots/api#getmycommands).
- [x] Added the method [`deleteMyCommands`](https://core.telegram.org/bots/api#deletemycommands) to allow deletion of the bot's commands for the given scope and user language.
- [x] Improved visibility of bot commands in Telegram apps with the new 'Menu' button in chats with bots, read more on the [blog](https://telegram.org/blog/animated-backgrounds#bot-menu).

## Custom Placeholders

- [x] Added the ability to specify a custom input field placeholder in the classes [`ReplyKeyboardMarkup`](https://core.telegram.org/bots/api#replykeyboardmarkup) and [`ForceReply`](https://core.telegram.org/bots/api#forcereply).

## And More

- [x] Improved documentation of the class [`ChatMember`](https://core.telegram.org/bots/api#chatmember) by splitting it into 6 subclasses.
- [x] Renamed the method `kickChatMember` to [`banChatMember`](https://core.telegram.org/bots/api#banchatmember). The old method name can still be used.
- [x] Renamed the method `getChatMembersCount` to [`getChatMemberCount`](https://core.telegram.org/bots/api#getchatmembercount). The old method name can still be used.
- [x] :warning: Values of the field `file_unique_id` in objects of the type [`PhotoSize`](https://core.telegram.org/bots/api#photosize) and of the fields `small_file_unique_id` and `big_file_unique_id` in objects of the type [`ChatPhoto`](https://core.telegram.org/bots/api#chatphoto) were changed.

> **:warning: WARNING! :warning:**
> After one of the upcoming Bot API updates, user identifiers will become bigger than `2**31 - 1` and it will be no longer possible to store them in a signed 32-bit integer type. User identifiers will have up to 52 significant bits, so a 64-bit integer or double-precision float type would still be safe for storing them. Please make sure that your code can correctly handle such user identifiers.
> This won't really affect you and your Python code as Python's `int` is big enough, but if you rely on other libraries/frameworks/code, make sure that Telegram User ID field has appropriate size, e.g. use `bigint` / `bigserial` instead of `int` / `integer` / `serial` in PostgreSQL.

**Comment by dmytrohoi** [comment]
The last necessary changes were added by #614.

Can you please merge #614 to #610 (dev-2.x-api-5.3 branch) to the API 5.3 coverage.
